// ***Bookings Today***
export const GET_BOOKINGS_TODAY = "GET_BOOKINGS_TODAY"
export const GET_BOOKINGS_TODAY_SUCCESS = "GET_BOOKINGS_TODAY_SUCCESS"
export const GET_BOOKINGS_TODAY_FAIL = "GET_BOOKINGS_TODAY_FAIL"

// ***Checked In Customer***
export const GET_CHECKEDIN_CUSTOMER_TODAY = "GET_CHECKEDIN_CUSTOMER_TODAY"
export const GET_CHECKEDIN_CUSTOMER_SUCCESS = "GET_CHECKEDIN_CUSTOMER_SUCCESS"
export const GET_CHECKEDIN_CUSTOMER_FAIL = "GET_CHECKEDIN_CUSTOMER_FAIL "